# Generated by Django 3.0.3 on 2020-02-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
