# Generated by Django 3.0.3 on 2020-02-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.TextField(default='sdsfsdfgsrgsg'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.News')),
            ],
        ),
    ]
