# Generated by Django 3.0.3 on 2020-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200214_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
