# Generated by Django 3.0.3 on 2020-02-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200215_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
